Create Join_on_labels.yaml
cncf/tag-observability pull request #111
Opened 2023-07-19 04:37 UTC by Olli73773

2023-07-21 16:48 UTC, manolama requested changes
Good! Just a couple of grammar tweaks.

2023-07-21 16:48 UTC, manolama commented on working-groups/query-standardization/use-cases/common/single_type/metrics/Join_on_labels.yaml
> +  filtering addition dimensions.
`s/addition/additional/`

2023-07-21 16:48 UTC, manolama commented on working-groups/query-standardization/use-cases/common/single_type/metrics/Join_on_labels.yaml
> +      Add additional the abillity to filter on additional dimensions or get addtional demension
Add ~~additional~~ the

2023-07-25 15:25 UTC, Olli73773 commented on working-groups/query-standardization/use-cases/common/single_type/metrics/Join_on_labels.yaml
> +      Add additional the abillity to filter on additional dimensions or get addtional demension
Fixed the grammar

2023-07-25 15:54 UTC, manolama approved these changes

2023-08-01 05:47 UTC, alolita approved these changes
+1

2023-08-01 05:47 UTC, merged